ManagementDispatch/Controllers/ManageTextToController.cs
using ManagementDispatch.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ManagementDispatch.Controllers
{
    [AuthorzireBusiness]
    public class ManageTextToController : Controller
    {
        // GET: Text
        DataBaseDataContext _data = new DataBaseDataContext();
        public ActionResult Index()
        {
            var getAllTextTo = _data.CongVanDens.Where(c => c.BaoMat==false).ToList();
            return View(getAllTextTo);
        }

        [HttpGet]
        public ActionResult AddTextTo()
        {
            ViewBag.IDLoaiCongVan = new SelectList(_data.LoaiCongVans.ToList().OrderBy(n => n.IDLoaiCongVan ), "IDLoaiCongVan", "TenLoaiCongVan");
            ViewBag.IDPhongBan = new SelectList(_data.PhongBans.ToList().OrderBy(n => n.IDPhongBan ), "IDPhongBan", "TenPhongBan");
            ViewBag.IDDonViGui = new SelectList(_data.DonVis.ToList().OrderBy(n => n.IDDonVi ), "IDDonVi", "TenDonVi");
            ViewBag.IDDonViNhan = new SelectList(_data.DonVis.ToList().OrderBy(n => n.IDDonVi ), "IDDonVi", "TenDonVi");

            return View();
        }



        [HttpPost]
        public ActionResult AddTextTo(CongVanDen item, FormCollection formCollection, HttpPostedFileBase uploadFile)
        {
            ViewBag.IDLoaiCongVan = new SelectList(_data.LoaiCongVans.ToList().OrderBy(n => n.IDLoaiCongVan ), "IDLoaiCongVan", "TenLoaiCongVan");
            ViewBag.IDPhongBan = new SelectList(_data.PhongBans.ToList().OrderBy(n => n.IDPhongBan ), "IDPhongBan", "TenPhongBan");
            ViewBag.IDDonViGui = new SelectList(_data.DonVis.ToList().OrderBy(n => n.IDDonVi ), "IDDonVi", "TenDonVi");
            ViewBag.IDDonViNhan = new SelectList(_data.DonVis.ToList().OrderBy(n => n.IDDonVi ), "IDDonVi", "TenDonVi");

            try
            {
                ViewBag.Validate = " ";

                var fileName = Path.GetFileName(uploadFile.FileName);
                //Luu duong dan File
                var path = Path.Combine(Server.MapPath("~/FileDocument"), fileName);
                if (System.IO.File.Exists(path))
                    ViewBag.Thongbao = "Hình ảnh đã tồn tại";
                else
                    uploadFile.SaveAs(path);//Luu file vao duong dan
                item.File = fileName;
                item.NgayGui = DateTime.Parse(formCollection["NgayGui"]);
                item.NgayNhan = DateTime.Parse(formCollection["NgayNhan"]);

                _data.CongVanDens.InsertOnSubmit(item);
                _data.SubmitChanges();

                string writeLog = "Thêm công văn đến: " + item.IDCongVanDen;
                NhanVien admin = (NhanVien)Session["Admin"];
                NhatKyHeThong log = new NhatKyHeThong();
                log.IDNhanVien = admin.IDNhanVien;
                log.NoiDungNhatKy = writeLog;
                log.NgayGio = DateTime.Now;
                _data.NhatKyHeThongs.InsertOnSubmit(log);
                _data.SubmitChanges();

                return RedirectToAction("Index");

            }
            catch
            {
                return View();
            }
        }
        public FileResult Download(string fileName)
        {

            string contentType = string.Empty;
            if (Path.GetExtension(fileName) == ".txt")
            {
                contentType = "application/txt";
            }

            else if (Path.GetExtension(fileName) == ".pdf")
            {
                contentType = "application/pdf";
            }
            else if (Path.GetExtension(fileName) == ".doc")
            {
                contentType = "application/msword";
            }
            else if (Path.GetExtension(fileName) == ".docx")
            {
                contentType = "application/vnd.openxmlformats-officedocument.wordprocessingml.document";
            }
            else
            {
                contentType = "unknown/unknown";
            }
            string fullPath = Path.Combine(Server.MapPath("~/FileDocument/"), fileName);
            return File(fullPath, contentType, fileName);
        }

        [HttpGet]
        public ActionResult EditTextTo(int id)
        {
            ViewBag.IDLoaiCongVan = new SelectList(_data.LoaiCongVans.ToList().OrderBy(n => n.TenLoaiCongVan), "IDLoaiCongVan", "TenLoaiCongVan");
            ViewBag.IDPhongBan = new SelectList(_data.PhongBans.ToList().OrderBy(n => n.TenPhongBan), "IDPhongBan", "TenPhongBan");
            ViewBag.IDDonViGui = new SelectList(_data.DonVis.ToList().OrderBy(n => n.TenDonVi), "IDDonVi", "TenDonVi");
            ViewBag.IDDonViNhan = new SelectList(_data.DonVis.ToList().OrderBy(n => n.TenDonVi), "IDDonVi", "TenDonVi");

            CongVanDen getTextTo = _data.CongVanDens.SingleOrDefault(c => c.STT == id);
            return View(getTextTo);
        }
        [HttpPost]
        public ActionResult EditTextTo(int id, FormCollection formCollection, HttpPostedFileBase uploadFile)
        {
            CongVanDen getTextTo = _data.CongVanDens.SingleOrDefault(c => c.STT == id);
           
            if (ModelState.IsValid)
            {
                    if (uploadFile != null)
                    {
                        //Luu ten file
                        var fileName = Path.GetFileName(uploadFile.FileName);
                        //Luu duong dan File
                        var path = Path.Combine(Server.MapPath("~/FileDocument"), fileName);
                        //Kiem tra hinh da ton tai chua\
                        if (System.IO.File.Exists(path))
                            ViewBag.Thongbao = "Hình ảnh đã tồn tại";
                        else
                            uploadFile.SaveAs(path);//Luu file vao duong dan

                        getTextTo.File = fileName;
                    }

            }
            int idLoaiCongVan = int.Parse(formCollection["IDLoaiCongVan"]);
            int idPhongBan = int.Parse(formCollection["IDPhongBan"]);
            int idDonViGui = int.Parse(formCollection["IDDonViGui"]);
            string noiDung = formCollection["NoiDung"];
            DateTime ngayGui = DateTime.Parse(formCollection["NgayGui"]);
            DateTime ngayNhan = DateTime.Parse(formCollection["NgayNhan"]);
            string tenNguoiNhan = formCollection["TenNguoiNhan"];
            string anhScan = formCollection["AnhScan"];

            getTextTo.IDLoaiCongVan = idLoaiCongVan;
            getTextTo.NoiDung = noiDung;
            getTextTo.NgayGui = ngayGui;
            getTextTo.NgayNhan = ngayNhan;
            getTextTo.IDPhongBan = idPhongBan;
            getTextTo.IDDonViGui = idDonViGui;
            getTextTo.TenNguoiNhan = tenNguoiNhan;
            getTextTo.AnhScan = anhScan;

            UpdateModel(getTextTo);
            _data.SubmitChanges();
            string writeLog = "Sửa công văn đi: " + getTextTo.IDCongVanDen;
            NhanVien admin = (NhanVien)Session["Admin"];
            NhatKyHeThong log = new NhatKyHeThong();
            log.IDNhanVien = admin.IDNhanVien;
            log.NoiDungNhatKy = writeLog;
            log.NgayGio = DateTime.Now;
            _data.NhatKyHeThongs.InsertOnSubmit(log);
            _data.SubmitChanges();
            return RedirectToAction("Index");
        }

        public string ChangeImage(int id,string picture)
        {
            CongVanDen textTo = _data.CongVanDens.FirstOrDefault(x => x.STT == id);
            if (textTo == null) return "Mã không tồn tại";
            textTo.AnhScan = picture;
            UpdateModel(textTo);
            _data.SubmitChanges();
            return "";
        }

        public bool DeleteText(int id)
        {
            try
            {
                var getTextTo = _data.CongVanDens.First(x => x.STT == id);
                _data.CongVanDens.DeleteOnSubmit(getTextTo);
                _data.SubmitChanges();

                string writeLog = "Xoá công văn đến: " + getTextTo.IDCongVanDen;
                NhanVien admin = (NhanVien)Session["Admin"];
                NhatKyHeThong log = new NhatKyHeThong();
                log.IDNhanVien = admin.IDNhanVien;
                log.NoiDungNhatKy = writeLog;
                log.NgayGio = DateTime.Now;
                _data.NhatKyHeThongs.InsertOnSubmit(log);
                _data.SubmitChanges();
                return true;
            }
            catch (Exception)
            {
                return false;
            }
        }
        //[HttpPost]
        public ActionResult Delete(int id)
        {
            try
            {
                var getTextTo = _data.CongVanDens.First(x => x.STT == id);
                string fullPath = "/FileDocument/" + Request.MapPath(getTextTo.File);
                if (System.IO.File.Exists(fullPath))
                {
                    System.IO.File.Delete(fullPath);
                }
                string fullPath2 = Request.MapPath(getTextTo.AnhScan);
                if (System.IO.File.Exists(fullPath2))
                {
                    System.IO.File.Delete(fullPath2);
                }
                _data.CongVanDens.DeleteOnSubmit(getTextTo);
                _data.SubmitChanges();

                string writeLog = "Xoá công văn đến: " + getTextTo.IDCongVanDen;
                NhanVien admin = (NhanVien)Session["Admin"];
                NhatKyHeThong log = new NhatKyHeThong();
                log.IDNhanVien = admin.IDNhanVien;
                log.NoiDungNhatKy = writeLog;
                log.NgayGio = DateTime.Now;
                _data.NhatKyHeThongs.InsertOnSubmit(log);
                _data.SubmitChanges();
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                return RedirectToAction("Index");
            }

        }
    }
}

ManagementDispatch/Views/ManageTextTo/AddTextTo.cshtml
@model ManagementDispatch.Models.CongVanDen
@{
    ViewBag.Title = "Thêm mới công văn";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="box box-solid">
    <div class="box-body">
        <h1>Thêm mới công văn</h1>
        <hr />
        @section jsFooter{
            <script>
        $('#btnSelectImage').on('click', function (e) {
            e.preventDefault;
            var finder = new CKFinder();
            finder.selectActionFunction = function (url) {
                $('#txtImage').val(url);
            };
            finder.popup();
        })
            </script>
            <script type="text/javascript">
        $(function () {
            $("#datepicker").datepicker({
                autoclose: true,
                todayHighlight: true
            }).datepicker('update', new Date());
        });
            </script>
            <script type="text/javascript">
        $(function () {
            $("#datepicker1").datepicker({
                autoclose: true,
                todayHighlight: true
            }).datepicker('update', new Date());
        });
            </script>
        }
        <style>
            #datepicker {
                width: 180px;
            }

                #datepicker > span:hover {
                    cursor: pointer;
                }

            #datepicker1 {
                width: 180px;
            }

                #datepicker1 > span:hover {
                    cursor: pointer;
                }
        </style>

        @using (Html.BeginForm("AddTextTo", "ManageTextTo", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()

        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.IDCongVanDen, "Số hiệu CV:", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.IDCongVanDen, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.IDCongVanDen, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.NgayNhan, "Ngày nhận", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div id="datepicker1" class="input-group date" data-date-format="dd-mm-yyyy">
                        <input class="form-control" readonly="" type="text" name="NgayNhan"> <span class="input-group-addon"><i class="glyphicon glyphicon-calendar"></i></span>
                    </div>
                    @Html.ValidationMessageFor(model => model.NgayNhan, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.IDDonViGui, "Đơn vị gửi: ", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.IDDonViGui, null, new { @class = "form-control" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.IDLoaiCongVan, "Loại công văn:", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.IDLoaiCongVan, null, new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.NgayGui, "Ngày gửi:", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div id="datepicker" class="input-group date" data-date-format="dd-mm-yyyy">
                        <input class="form-control" readonly="" type="text" name="NgayGui"> <span class="input-group-addon"><i class="glyphicon glyphicon-calendar"></i></span>
                    </div>

                    @Html.ValidationMessageFor(model => model.NgayGui, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.NoiDung, "Nội dung:", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.NoiDung, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.NoiDung, "", new { @class = "text-danger" })
                </div>
            </div>

            
            <div class="form-group">
                @Html.LabelFor(model => model.TenNguoiNhan, "Người nhận: ", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.TenNguoiNhan, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.TenNguoiNhan, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.IDPhongBan, "Tên phòng ban:", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.IDPhongBan, null, new { @class = "form-control" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.BaoMat, "Văn bản bảo mật:", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.CheckBoxFor(model => model.BaoMat, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.BaoMat, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.File, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <input type="file" name="uploadFile" />
                    @ViewBag.Thongbao
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.AnhScan, "Ảnh scan( 1 ảnh): ", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextBoxFor(model => model.AnhScan, new { htmlAttributes = new { @class = "form-control", @id = "txtImage" }, id = "txtImage" })
                    <a id="btnSelectImage" href="#">Chọn ảnh</a>
                    @Html.ValidationMessageFor(model => model.AnhScan, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Tạo mới" class="btn btn-default" />
                </div>
            </div>
        </div>
        }
    </div>
</div>
<script type="text/javascript">
    $(function () {
        // This will make every element with the class "date-picker" into a DatePicker element
        $('.date-picker').datepicker();
    })
</script>

ManagementDispatch/Views/ManageTextTo/EditTextTo.cshtml
@model ManagementDispatch.Models.CongVanDen
@{
    ViewBag.Title = "Sửa công văn";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section jsFooter{
    <script>
        $('#btnSelectImage').on('click', function (e) {
            e.preventDefault;
            var finder = new CKFinder();
            finder.selectActionFunction = function (url) {
                $('#txtImage').val(url);
            };
            finder.popup();
        })
    </script>
    <script type="text/javascript">
        $(function () {
            $("#datepicker").datepicker({
                autoclose: true,
                todayHighlight: true
            }).datepicker('update', new Date());
        });
    </script>
    <script type="text/javascript">
        $(function () {
            $("#datepicker1").datepicker({
                autoclose: true,
                todayHighlight: true
            }).datepicker('update', new Date());
        });
    </script>
}
<style>
    #datepicker {
        width: 180px;
    }

        #datepicker > span:hover {
            cursor: pointer;
        }

    #datepicker1 {
        width: 180px;
    }

        #datepicker1 > span:hover {
            cursor: pointer;
        }
</style>

<div class="box box-solid">
    <div class="box-body">
        <h1>Sửa công văn</h1>
        <hr />
        @using (Html.BeginForm("EditTextTo", "ManageTextTo", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()

        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.IDCongVanDen, "Số hiệu CV:", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.IDCongVanDen, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.IDCongVanDen, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.NgayNhan, "Ngày nhận", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    
                    <input type="date" name="NgayNhan" id="NgayNhan" class="form-control" value="@Model.NgayNhan.ToString(string.Format("yyyy-MM-dd"))" />
                    @Html.ValidationMessageFor(model => model.NgayNhan, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.IDDonViGui, "Đơn vị gửi: ", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.IDDonViGui, null, new { @class = "form-control" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.IDLoaiCongVan, "Loại công văn:", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.IDLoaiCongVan, null, new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.NgayGui, "Ngày gửi:", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <input type="date" name="NgayGui" id="NgayGui" class="form-control" value="@Model.NgayGui.ToString(string.Format("yyyy-MM-dd"))"/>
                    @Html.ValidationMessageFor(model => model.NgayGui, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.NoiDung, "Nội dung:", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.NoiDung, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.NoiDung, "", new { @class = "text-danger" })
                </div>
            </div>


            <div class="form-group">
                @Html.LabelFor(model => model.TenNguoiNhan, "Người nhận: ", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.TenNguoiNhan, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.TenNguoiNhan, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.IDPhongBan, "Tên phòng ban:", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.IDPhongBan, null, new { @class = "form-control" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.BaoMat, "Văn bản bảo mật:", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.CheckBoxFor(model => model.BaoMat, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.BaoMat, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.File, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <input type="file" name="uploadFile" />
                    @ViewBag.Thongbao
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.AnhScan, "Ảnh scan( 1 ảnh): ", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextBoxFor(model => model.AnhScan, new { htmlAttributes = new { @class = "form-control", @id = "txtImage" }, id = "txtImage" })
                    <a id="btnSelectImage" href="#">Chọn ảnh</a>
                    @Html.ValidationMessageFor(model => model.AnhScan, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Sửa" class="btn btn-default" />
                </div>
            </div>
        </div>
        }
    </div>
</div>
<script type="text/javascript">
    $(function () {
        // This will make every element with the class "date-picker" into a DatePicker element
        $('.date-picker').datepicker();
    })
</script>

ManagementDispatch/Views/ManageTextTo/Index.cshtml
@model IEnumerable<ManagementDispatch.Models.CongVanDen>
@{
    ViewBag.Title = "Các công văn đến";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="box box-solid">
    <div class="box-body">
        <h1>Các công văn đến</h1>
        <hr />
        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">


                    @Html.ActionLink("Thêm mới", "AddTextTo", "Admin", htmlAttributes: new { @class = "btn btn-primary" })

                    <div class="panel-body">
                        <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example-textto">
                            <thead>
                                <tr>
                                    <th style="width:1%">STT</th>
                                    <th>Ngày nhận</th>
                                    <th>Nơi gửi</th>
                                    <th style="width:7%">Số CV</th>
                                    <th>Loại CV</th>
                                    <th>Ngày gửi</th>
                                    <th>Nội dung</th>
                                    <th>Người nhận</th>
                                    <th>Phòng ban</th>
                                    <th>File</th>
                                    <th>Ảnh Scan</th>
                                    <th style="width:11%">Chức năng</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr id="row_@item.STT">
                                        <td>@item.STT</td>
                                        <td>@item.NgayNhan.ToString(string.Format("dd/MM/yyyy"))</td>
                                        <td>@item.DonVi.TenDonVi</td>
                                        <td>@item.IDCongVanDen</td>
                                        <td>@item.LoaiCongVan.TenLoaiCongVan</td>
                                        <td>@item.NgayGui.ToString(string.Format("dd/MM/yyyy"))</td>
                                        <td>@item.NoiDung</td>
                                        <td>@item.TenNguoiNhan</td>
                                        <td>@item.PhongBan.TenPhongBan</td>
                                        <td>@Html.ActionLink("Download", "Download", new { fileName = item.File })</td>
                                        <td style="width:60px"><img style="cursor:pointer" id="img_@item.IDCongVanDen" src="@Url.Content("~/"+item.AnhScan)" width="60" height="50" @*onclick="selectImage('ManageTextTo/ChangeTextTo/@item.IDCongVanDen',this.id)"*@></td>
                                        <td>
                                            @Html.ActionLink("Sửa", "EditTextTo", new { id = item.STT }, htmlAttributes: new { @class = "btn btn-primary" }) |
                                            @Ajax.ActionLink("Xóa","Delete",new { @id = item.STT},new AjaxOptions
                                           {
                                               Confirm = "Bạn có muốn xóa công văn này?",
                                               OnComplete = "$('#row_"+@item.STT+"').remove()",
                                               HttpMethod = "Delete"
                                           }, htmlAttributes: new { @class = "btn btn-danger" })
                                            |
                                            @Html.ActionLink("Delete", "Delete", new { id = item.STT }, new { onclick = "return confirm('Are sure wants to delete?');" , @class = "btn btn-danger" })
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
                <!-- /.panel -->
            </div>
            <!-- /.col-lg-12 -->
        </div>
    </div>
</div>
<script>
    $(document).ready(function () {
        $('#dataTables-example-textto').DataTable({
            responsive: true
        });
    });
</script>
@*<script>
        function selectImage(action,id)
        {
            var finder = new CKFinder();
            finder.selectActionFunction = function(fileUrl){
              $.ajax({
                    method: "GET",
                    url: action,
                    data: {picture:fileUrl}
                }).done(function (path){
                    if(path!=""){
                        alert("Lỗi cập nhật hình ảnh:" + path);
                    }
                    else{
                        $("#"+id).attr("src",fileUrl);
                    }
                });
            };
            finder.popup();
        }
    </script>*@