ManagementDispatch/Controllers/ManageTextGoController.cs
using ManagementDispatch.Models;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ManagementDispatch.Controllers
{
    [AuthorzireBusiness]
    public class ManageTextGoController : Controller
    {
        // GET: Text
        DataBaseDataContext _data = new DataBaseDataContext();
        public ActionResult Index()
        {
            var getAllTextTo = _data.CongVanDis.Where(c => c.BaoMat == false).ToList();
            return View(getAllTextTo);
        }

        [HttpGet]
        public ActionResult AddTextGo()
        {
            ViewBag.IDLoaiCongVan = new SelectList(_data.LoaiCongVans.ToList().OrderBy(n => n.IDLoaiCongVan), "IDLoaiCongVan", "TenLoaiCongVan");
            ViewBag.IDDonViGui = new SelectList(_data.DonVis.ToList().OrderBy(n => n.IDDonVi ), "IDDonVi", "TenDonVi");
            ViewBag.IDDonViNhan = new SelectList(_data.DonVis.ToList().OrderBy(n => n.IDDonVi ), "IDDonVi", "TenDonVi");
            ViewBag.IDPhongBan = new SelectList(_data.PhongBans.ToList().OrderBy(n => n.IDPhongBan ), "IDPhongBan", "TenPhongBan");
            return View();
        }



        [HttpPost]
        public ActionResult AddTextGo(CongVanDi item, FormCollection formCollection, HttpPostedFileBase uploadFile)
        {
            ViewBag.IDLoaiCongVan = new SelectList(_data.LoaiCongVans.ToList().OrderBy(n => n.IDLoaiCongVan ), "IDLoaiCongVan", "TenLoaiCongVan");
            ViewBag.IDDonViGui = new SelectList(_data.DonVis.ToList().OrderBy(n => n.IDDonVi ), "IDDonVi", "TenDonVi");
            ViewBag.IDDonViNhan = new SelectList(_data.DonVis.ToList().OrderBy(n => n.IDDonVi ), "IDDonVi", "TenDonVi");
            ViewBag.IDPhongBan = new SelectList(_data.PhongBans.ToList().OrderBy(n => n.IDPhongBan ), "IDPhongBan", "TenPhongBan");
            try
            {
                ViewBag.Validate = " ";

                var fileName = Path.GetFileName(uploadFile.FileName);
                if (fileName != null)
                {
                    var path = Path.Combine(Server.MapPath("~/FileDocument"), fileName);
                    if (System.IO.File.Exists(path))
                        ViewBag.Thongbao = "Tập tin đã tồn tại";
                    else
                        uploadFile.SaveAs(path);//Luu file vao duong dan
                    item.File = fileName;
                }
                else
                {
                    item.File = "";
                }
                //Luu duong dan File

                item.NgayGui = DateTime.Parse(formCollection["NgayGui"]);
                _data.CongVanDis.InsertOnSubmit(item);
                _data.SubmitChanges();

                string writeLog = "Thêm công văn đi: " + item.IDCongVanDi;
                NhanVien admin = (NhanVien)Session["Admin"];
                NhatKyHeThong log = new NhatKyHeThong();
                log.IDNhanVien = admin.IDNhanVien;
                log.NoiDungNhatKy = writeLog;
                log.NgayGio = DateTime.Now;
                _data.NhatKyHeThongs.InsertOnSubmit(log);
                _data.SubmitChanges();

                return RedirectToAction("Index");

            }
            catch
            {
                return View();
            }
        }
        public FileResult Download(string fileName)
        {

            string contentType = string.Empty;

            if (Path.GetExtension(fileName) == ".txt")
            {
                contentType = "application/txt";
            }

            else if (Path.GetExtension(fileName) == ".pdf")
            {
                contentType = "application/pdf";
            }
            else if (Path.GetExtension(fileName) == ".doc")
            {
                contentType = "application/msword";
            }
            else if (Path.GetExtension(fileName) == ".docx")
            {
                contentType = "application/vnd.openxmlformats-officedocument.wordprocessingml.document";
            }
            else
            {
                contentType = "unknown/unknown";
            }
            string fullPath = Path.Combine(Server.MapPath("~/FileDocument/"), fileName);
            return File(fullPath, contentType, fileName);
        }

        [HttpGet]
        public ActionResult EditTextGo(int id)
        {
            ViewBag.IDLoaiCongVan = new SelectList(_data.LoaiCongVans.ToList().OrderBy(n => n.TenLoaiCongVan), "IDLoaiCongVan", "TenLoaiCongVan");
            ViewBag.IDPhongBan = new SelectList(_data.PhongBans.ToList().OrderBy(n => n.TenPhongBan), "IDPhongBan", "TenPhongBan");
            ViewBag.IDDonViGui = new SelectList(_data.DonVis.ToList().OrderBy(n => n.TenDonVi), "IDDonVi", "TenDonVi");
            ViewBag.IDDonViNhan = new SelectList(_data.DonVis.ToList().OrderBy(n => n.TenDonVi), "IDDonVi", "TenDonVi");

            CongVanDi getTextGo = _data.CongVanDis.SingleOrDefault(c => c.STT == id);
            return View(getTextGo);
        }
        [HttpPost]
        public ActionResult EditTextGo(int id, FormCollection formCollection, HttpPostedFileBase uploadFile)
        {
            CongVanDi getTextGo = _data.CongVanDis.SingleOrDefault(c => c.STT == id);
            if (ModelState.IsValid)
            {
                if (uploadFile != null)
                {
                    //Luu ten file
                    var fileName = Path.GetFileName(uploadFile.FileName);
                    //Luu duong dan File
                    var path = Path.Combine(Server.MapPath("~/FileDocument"), fileName);
                    //Kiem tra hinh da ton tai chua\
                    if (System.IO.File.Exists(path))
                        ViewBag.Thongbao = "Hình ảnh đã tồn tại";
                    else
                        uploadFile.SaveAs(path);//Luu file vao duong dan

                    getTextGo.File = fileName;
                }
            }
            int idLoaiCongVan = int.Parse(formCollection["IDLoaiCongVan"]);
            int idDonViGui = int.Parse(formCollection["IDDonViGui"]);
            string noiDung = formCollection["NoiDungCongViec"];
            DateTime ngayGui = DateTime.Parse(formCollection["NgayGui"]);
            string tenNguoiGui = formCollection["TenNguoiGui"];
            string anhScan = formCollection["AnhScan"];

            getTextGo.IDLoaiCongVan = idLoaiCongVan;
            getTextGo.NoiDungCongViec = noiDung;
            getTextGo.NgayGui = ngayGui;
            getTextGo.TenNguoiGui = tenNguoiGui;
            getTextGo.IDDonViGui = idDonViGui;
            getTextGo.AnhScan = anhScan;

            UpdateModel(getTextGo);
            _data.SubmitChanges();

            string writeLog = "Sửa công văn đi: " + getTextGo.IDCongVanDi;
            NhanVien admin = (NhanVien)Session["Admin"];
            NhatKyHeThong log = new NhatKyHeThong();
            log.IDNhanVien = admin.IDNhanVien;
            log.NoiDungNhatKy = writeLog;
            log.NgayGio = DateTime.Now;
            _data.NhatKyHeThongs.InsertOnSubmit(log);
            _data.SubmitChanges();


            return RedirectToAction("Index");
        }
        public bool DeleteText(int id)
        {
            try
            {
                var getTextGo = _data.CongVanDis.First(x => x.STT == id);
                string fullPath = "/FileDocument/" + Request.MapPath(getTextGo.File);
                if (System.IO.File.Exists(fullPath))
                {
                    System.IO.File.Delete(fullPath);
                }
                string fullPath2 = Request.MapPath(getTextGo.AnhScan);
                if (System.IO.File.Exists(fullPath2))
                {
                    System.IO.File.Delete(fullPath2);
                }
                _data.CongVanDis.DeleteOnSubmit(getTextGo);
                _data.SubmitChanges();

                string writeLog = "Xoá công văn đi: " + getTextGo.IDCongVanDi;
                NhanVien admin = (NhanVien)Session["Admin"];
                NhatKyHeThong log = new NhatKyHeThong();
                log.IDNhanVien = admin.IDNhanVien;
                log.NoiDungNhatKy = writeLog;
                log.NgayGio = DateTime.Now;

                _data.NhatKyHeThongs.InsertOnSubmit(log);
                _data.SubmitChanges();
                return true;
            }
            catch (Exception)
            {
                return false;
            }
        }
        public ActionResult Delete(int id)
        {
            DeleteText(id);
            return RedirectToAction("Index");
        }
    }
}

ManagementDispatch/Controllers/ManageTextSecretController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ManagementDispatch.Models;
namespace ManagementDispatch.Controllers
{
    [AuthorzireBusiness]
    public class ManageTextSecretController : Controller
    {
        DataBaseDataContext _data = new DataBaseDataContext();
        // GET: ManageTextSecret
       public ActionResult Index()
        {
            return View();
        }

        public ActionResult TextToSecret()
        {
            var getListTextToSecret = _data.CongVanDens.Where(x => x.BaoMat == true).ToList();

            return PartialView(getListTextToSecret);
        }

        public ActionResult TextGoSecret()
        {
            var getListTextGoSecret = _data.CongVanDis.Where(x => x.BaoMat == true).ToList();

            return PartialView(getListTextGoSecret);
        }
        [HttpGet]
        public ActionResult EditTextToSecret(int id)
        {
            ViewBag.IDLoaiCongVan = new SelectList(_data.LoaiCongVans.ToList().OrderBy(n => n.TenLoaiCongVan), "IDLoaiCongVan", "TenLoaiCongVan");
            ViewBag.IDPhongBan = new SelectList(_data.PhongBans.ToList().OrderBy(n => n.TenPhongBan), "IDPhongBan", "TenPhongBan");
            ViewBag.IDDonViGui = new SelectList(_data.DonVis.ToList().OrderBy(n => n.TenDonVi), "IDDonVi", "TenDonVi");
            ViewBag.IDDonViNhan = new SelectList(_data.DonVis.ToList().OrderBy(n => n.TenDonVi), "IDDonVi", "TenDonVi");

            CongVanDen getTextTo = _data.CongVanDens.SingleOrDefault(c => c.STT == id);
            return View(getTextTo);
        }
        [HttpPost]
        public ActionResult EditTextToSecret(int id, FormCollection formCollection, HttpPostedFileBase uploadFile)
        {
            CongVanDen getTextTo = _data.CongVanDens.SingleOrDefault(c => c.STT == id);

            if (ModelState.IsValid)
            {
                    if (uploadFile != null)
                    {
                        //Luu ten file
                        var fileName = Path.GetFileName(uploadFile.FileName);
                        //Luu duong dan File
                        var path = Path.Combine(Server.MapPath("~/FileDocument"), fileName);
                        //Kiem tra hinh da ton tai chua\
                        if (System.IO.File.Exists(path))
                            ViewBag.Thongbao = "Hình ảnh đã tồn tại";
                        else
                            uploadFile.SaveAs(path);//Luu file vao duong dan

                        getTextTo.File = fileName;
                    }

            }
            int idLoaiCongVan = int.Parse(formCollection["IDLoaiCongVan"]);
            int idPhongBan = int.Parse(formCollection["IDPhongBan"]);
            int idDonViGui = int.Parse(formCollection["IDDonViGui"]);
            int idDonViNhan = int.Parse(formCollection["IDDonViNhan"]);
            string noiDung = formCollection["NoiDung"];
            DateTime ngayGui = DateTime.Parse(formCollection["NgayGui"]);
            DateTime ngayNhan = DateTime.Parse(formCollection["NgayNhan"]);
            string tenNguoiGui = formCollection["TenNguoiGui"];
            string tenNguoiNhan = formCollection["TenNguoiNhan"];
            string anhScan = formCollection["AnhScan"];

            getTextTo.IDLoaiCongVan = idLoaiCongVan;
            getTextTo.NoiDung = noiDung;
            getTextTo.NgayGui = ngayGui;
            getTextTo.NgayNhan = ngayNhan;
            getTextTo.TenNguoiGui = tenNguoiGui;
            getTextTo.IDPhongBan = idPhongBan;
            getTextTo.IDDonViGui = idDonViGui;
            getTextTo.IDDonViNhan = idDonViNhan;
            getTextTo.TenNguoiNhan = tenNguoiNhan;
            getTextTo.AnhScan = anhScan;

            UpdateModel(getTextTo);
            _data.SubmitChanges();
            string writeLog = "Sửa công văn đi: " + getTextTo.IDCongVanDen;
            NhanVien admin = (NhanVien)Session["Admin"];
            NhatKyHeThong log = new NhatKyHeThong();
            log.IDNhanVien = admin.IDNhanVien;
            log.NoiDungNhatKy = writeLog;
            log.NgayGio = DateTime.Now;
            _data.NhatKyHeThongs.InsertOnSubmit(log);
            _data.SubmitChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult EditTextGoSecret(int id)
        {
            ViewBag.IDLoaiCongVan = new SelectList(_data.LoaiCongVans.ToList().OrderBy(n => n.TenLoaiCongVan), "IDLoaiCongVan", "TenLoaiCongVan");
            ViewBag.IDPhongBan = new SelectList(_data.PhongBans.ToList().OrderBy(n => n.TenPhongBan), "IDPhongBan", "TenPhongBan");
            ViewBag.IDDonViGui = new SelectList(_data.DonVis.ToList().OrderBy(n => n.TenDonVi), "IDDonVi", "TenDonVi");
            ViewBag.IDDonViNhan = new SelectList(_data.DonVis.ToList().OrderBy(n => n.TenDonVi), "IDDonVi", "TenDonVi");

            CongVanDi getTextGo = _data.CongVanDis.SingleOrDefault(c => c.STT == id);
            return View(getTextGo);
        }
        [HttpPost]
        public ActionResult EditTextGoSecret(int id, FormCollection formCollection, HttpPostedFileBase uploadFile)
        {
            CongVanDi getTextGo = _data.CongVanDis.SingleOrDefault(c => c.STT == id);

            if (ModelState.IsValid)
            {
                if (uploadFile != null)
                {
                    //Luu ten file
                    var fileName = Path.GetFileName(uploadFile.FileName);
                    //Luu duong dan File
                    var path = Path.Combine(Server.MapPath("~/FileDocument"), fileName);
                    //Kiem tra hinh da ton tai chua\
                    if (System.IO.File.Exists(path))
                        ViewBag.Thongbao = "Hình ảnh đã tồn tại";
                    else
                        uploadFile.SaveAs(path);//Luu file vao duong dan

                    getTextGo.File = fileName;
                }
            }
            int idLoaiCongVan = int.Parse(formCollection["IDLoaiCongVan"]);
            int idDonViGui = int.Parse(formCollection["IDDonViGui"]);
            string noiDung = formCollection["NoiDungCongViec"];
            DateTime ngayGui = DateTime.Parse(formCollection["NgayGui"]);
            string tenNguoiGui = formCollection["TenNguoiGui"];
            string anhScan = formCollection["AnhScan"];

            getTextGo.IDLoaiCongVan = idLoaiCongVan;
            getTextGo.NoiDungCongViec = noiDung;
            getTextGo.NgayGui = ngayGui;
            getTextGo.TenNguoiGui = tenNguoiGui;
            getTextGo.IDDonViGui = idDonViGui;
            getTextGo.AnhScan = anhScan;

            UpdateModel(getTextGo);
            _data.SubmitChanges();

            string writeLog = "Sửa công văn đi: " + getTextGo.IDCongVanDi;
            NhanVien admin = (NhanVien)Session["Admin"];
            NhatKyHeThong log = new NhatKyHeThong();
            log.IDNhanVien = admin.IDNhanVien;
            log.NoiDungNhatKy = writeLog;
            log.NgayGio = DateTime.Now;
            _data.NhatKyHeThongs.InsertOnSubmit(log);
            _data.SubmitChanges();


            return RedirectToAction("Index");
        }
    }
}

ManagementDispatch/Views/ManageTextSecret/EditTextGoSecret.cshtml
@model ManagementDispatch.Models.CongVanDi
@{
    /**/

    ViewBag.Title = "Sửa công văn mật";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<p style="font-size:30px">Sửa công văn mật</p>
<hr />
@section jsFooter{
    <script>
        $('#btnSelectImage').on('click', function (e) {
            e.preventDefault;
            var finder = new CKFinder();
            finder.selectActionFunction = function (url) {
                $('#txtImage').val(url);
            };
            finder.popup();
        })
    </script>
    <script type="text/javascript">
        $(function () {
            $("#datepicker").datepicker({
                autoclose: true,
                todayHighlight: true
            }).datepicker('update', new Date());
        });
    </script>
    <script type="text/javascript">
        $(function () {
            $("#datepicker1").datepicker({
                autoclose: true,
                todayHighlight: true
            }).datepicker('update', new Date());
        });
    </script>
}
<style>
    #datepicker {
        width: 180px;
    }

        #datepicker > span:hover {
            cursor: pointer;
        }

    #datepicker1 {
        width: 180px;
    }

        #datepicker1 > span:hover {
            cursor: pointer;
        }
</style>

@using (Html.BeginForm("EditTextGoSecret", "ManageTextSecret", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.IDCongVanDi, "Số hiệu CV:", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IDCongVanDi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IDCongVanDi, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.IDLoaiCongVan, "Loại công văn:", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.IDLoaiCongVan, null, new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.IDDonViGui, "Đơn vị gửi: ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.IDDonViGui, null, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IDDonViGui, "Phòng ban: ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.IDPhongBan, null, new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.TenNguoiGui, "Người gửi: ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenNguoiGui, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenNguoiGui, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.NoiDungCongViec, "Nội dung:", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NoiDungCongViec, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NoiDungCongViec, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NgayGui, "Ngày gửi:", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NgayGui, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NgayGui, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.BaoMat, "Văn bản bảo mật:", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.CheckBoxFor(model => model.BaoMat, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BaoMat, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.File, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.File, new { htmlAttributes = new { @class = "form-control", disabled = "true" } })
                <p>chọn tập tin mới</p>
                <input type="file" name="uploadFile" />
                @ViewBag.Thongbao
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AnhScan, "Ảnh scan( 1 ảnh): ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.AnhScan, new { htmlAttributes = new { @class = "form-control", @id = "txtImage" }, id = "txtImage" })
                <a id="btnSelectImage" href="#">Chọn ảnh</a>
                @Html.ValidationMessageFor(model => model.AnhScan, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Sửa" class="btn btn-default" />
            </div>
        </div>
    </div>
}
<script type="text/javascript">
    $(function () {
        // This will make every element with the class "date-picker" into a DatePicker element
        $('.date-picker').datepicker();
    })
</script>

ManagementDispatch/Views/ManageTextSecret/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@Html.Action("TextToSecret", "ManageTextSecret")
@Html.Action("TextGoSecret", "ManageTextSecret")

ManagementDispatch/Views/ManageTextSecret/TextGoSecret.cshtml
@model IEnumerable<ManagementDispatch.Models.CongVanDi>

<div class="col-md-3 col-sm-6 col-xs-12">
    <div class="info-box">
        <span class="info-box-icon bg-red"><i class="fa fa-files-o"></i></span>

        <div class="info-box-content">
            <span class="info-box-text">Số công văn đi </span>
            <span class="info-box-number">@Model.Count()</span>
        </div>
        <!-- /.info-box-content -->
    </div>
    <!-- /.info-box -->
</div>
<hr />
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">

            <div class="panel-body">
                <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example3">
                    <thead>
                        <tr>
                            <th>STT</th>
                            <th>Ngày gửi</th>
                            <th>Số CV</th>
                            <th>Loại CV</th>
                            <th>Nội dung CV</th>
                            <th>Phòng ban</th>
                            <th>Người gửi</th>
                            <th>Nơi gửi</th>
                            <th>File</th>
                            <th>Ảnh scan</th>
                            <th>Chức năng</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>@item.STT</td>
                                <td class="center">@item.NgayGui.ToString(string.Format("dd/MM/yyyy"))</td>
                                <td class="center">@item.IDCongVanDi</td>
                                <td class="center">@item.LoaiCongVan.TenLoaiCongVan</td>
                                <td class="center">@item.NoiDungCongViec</td>
                                <td>@item.PhongBan.TenPhongBan</td>
                                <td class="center">@item.TenNguoiGui</td>
                                <td class="center">@item.DonVi.TenDonVi</td>
                                <td class="center">@Html.ActionLink("Download", "Download", new { fileName = item.File })</td>
                                <td style="width:60px"> <img src="@Url.Content("~/"+item.AnhScan)" width="60px" height="50px"></td>
                                <td>
                                    @Html.ActionLink("Sửa", "EditTextGoSecret", new { id = item.STT }, htmlAttributes: new { @class = "btn btn-primary" }) |
                                    @Ajax.ActionLink("Xóa","Delete","ManageTextGo",new { @id = item.STT},new AjaxOptions
                                       {
                                           Confirm = "Bạn có muốn xóa công văn này?",
                                           OnComplete = "$('#row_"+@item.STT+"').remove()",
                                           HttpMethod = "Delete"
                                       }, htmlAttributes: new { @class = "btn btn-danger" })
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>
<script>
    $(document).ready(function () {
        $('#dataTables-example3').DataTable({
            responsive: true
        });
    });
</script>